# Generated by Django 4.0.4 on 2022-05-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_uploadmodel',
            name='file_size',
            field=models.BigIntegerField(help_text='file_size'),
        ),
    ]
