# Generated by Django 4.0.4 on 2022-05-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_file_uploadmodel_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_uploadmodel',
            name='file_uploaded_date',
        ),
        migrations.AddField(
            model_name='file_uploadmodel',
            name='file_uploded_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
