# Generated by Django 4.0.4 on 2022-05-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_file_uploadmodel_file_uploaded_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_uploadmodel',
            name='status',
            field=models.CharField(default='pending', max_length=50, null='True'),
            preserve_default='True',
        ),
    ]
