# Generated by Django 4.0.4 on 2022-05-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_file_uploadmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='status',
            field=models.CharField(default='pending', max_length=50, null='True'),
            preserve_default='True',
        ),
    ]
