# Generated by Django 4.0.4 on 2022-05-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_usermodel_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_uploadmodel',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
