# Generated by Django 4.0.4 on 2022-05-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_file_uploadmodel_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_uploadmodel',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
