# Generated by Django 4.0.4 on 2022-05-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_file_uploadmodel_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_uploadmodel',
            name='file_download',
            field=models.CharField(help_text='file_download', max_length=300, null=True),
        ),
    ]
