# Generated by Django 4.0.4 on 2022-05-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_file_uploadmodel_file_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_uploadmodel',
            name='file_download',
        ),
    ]
