# Generated by Django 4.0.4 on 2022-05-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_remove_file_uploadmodel_file_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_downloadModel',
            fields=[
                ('file_download_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('file_uploded_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'download_details',
            },
        ),
    ]
